// This file was auto-generated by ML.NET Model Builder. 

using System;
using Machine_learning_csharpML.Model;

namespace Machine_learning_csharpML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Fixed_acidity = 7F,
                Volatile_acidity = 0.27F,
                Citric_acid = 0.36F,
                Residual_sugar = 20.7F,
                Chlorides = 0.045F,
                Free_sulfur_dioxide = 45F,
                Total_sulfur_dioxide = 170F,
                Density = 1.001F,
                PH = 3F,
                Sulphates = 0.45F,
                Alcohol = @"8.8",
                Quality = 6F,
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Type with predicted Type from sample data...\n\n");
            Console.WriteLine($"Fixed_acidity: {sampleData.Fixed_acidity}");
            Console.WriteLine($"Volatile_acidity: {sampleData.Volatile_acidity}");
            Console.WriteLine($"Citric_acid: {sampleData.Citric_acid}");
            Console.WriteLine($"Residual_sugar: {sampleData.Residual_sugar}");
            Console.WriteLine($"Chlorides: {sampleData.Chlorides}");
            Console.WriteLine($"Free_sulfur_dioxide: {sampleData.Free_sulfur_dioxide}");
            Console.WriteLine($"Total_sulfur_dioxide: {sampleData.Total_sulfur_dioxide}");
            Console.WriteLine($"Density: {sampleData.Density}");
            Console.WriteLine($"PH: {sampleData.PH}");
            Console.WriteLine($"Sulphates: {sampleData.Sulphates}");
            Console.WriteLine($"Alcohol: {sampleData.Alcohol}");
            Console.WriteLine($"Quality: {sampleData.Quality}");
            Console.WriteLine($"\n\nPredicted Type value {predictionResult.Prediction} \nPredicted Type scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
